url: https://louisdcoleman.github.io
# baseurl: /agency-jekyll-theme/

# Site settings
title: Louis D Coleman
email: lcoleman006@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Louis Coleman
  pic: 5
  position: Lead Developer, Engineer, Physicist
  social:
    - title: facebook
      url: https://www.facebook.com/louis.d.coleman
    - title: stack-overflow
      url: http://stackoverflow.com/questions/tagged/louisdcoleman
    - title: github
      url: https://github.com/LouisDColeman

- name: Susanne Jensen
  pic: 3
  position: Chemical Engineer
  social:
    - title: facebook
      url: https://www.facebook.com/susannehelene.jensen
    - title: linkedin
      url: https://www.linkedin.com/in/susanne-helene-jensen-a231a140

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/louis.d.coleman
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/louisdcoleman
  - title: github
    url: https://github.com/LouisDColeman

# Postal address (add as many lines as necessary)
address:
  - line: 1136 Oakheath Drive
  - line: Harbor City, CA 90710

# Build settings
markdown: kramdown
permalink: pretty
