enforce_ssl: https://louiscoleman.me

# url: https://louiscoleman.me
# baseurl: /agency-jekyll-theme/

# Site settings
title: Louis Coleman
email: lcoleman006@gmail.com
description: "Louis Coleman, a highly motivated entrepreneur, developer, engineer, and physicist that aims to work with companies that are looking for an edge."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 3f4e85
  primary-background: 222
  primary-text: ffffff
  primary-text-tint: 949490
  secondary: c9cee0
  secondary-background: f7f7f7
  secondary-dark: 333
  tertiary: fed136
  quaternary: 2e3141
  # secondary: fec503

# Team names, titles and social links
people:
- name: Louis Coleman
  pic: 5
  position: Developer, Engineer, Physicist
  social:
    - title: facebook
      url: https://www.facebook.com/louis.d.coleman
    # - title: stack-overflow
    #   url: http://stackoverflow.com/questions/tagged/louisdcoleman
    - title: github
      url: https://github.com/LouisDColeman

# - name: Susanne Jensen
#   pic: 4
#   position: Previous Member, Chemical Engineer
#   social:
#     - title: facebook
#       url: https://www.facebook.com/susannehelene.jensen
#     - title: linkedin
#       url: https://www.linkedin.com/in/susanne-helene-jensen-a231a140

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/louis.d.coleman
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/louisdcoleman
  - title: github
    url: https://github.com/LouisDColeman

# Postal address (add as many lines as necessary)
address:
  - line: 1136 Oakheath Drive
  - line: Harbor City, CA 90710

# Build settings
markdown: kramdown
permalink: pretty
